services:
  - type: web
    name: laravel-app
    runtime: ubuntu
    plan: free
    env: production
    buildCommand: |
      apt-get update && apt-get install -y php-cli php-mbstring php-xml php-bcmath php-curl unzip curl nginx php-fpm
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: |
      php-fpm -D && nginx -g "daemon off;"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
